### ISSUE TITLE
Add ! in front (extended image syntax) for whitelisted sites

### ISSUE THREAD

**Issue by kristofferR** [denolehov/obsidian-url-into-selection#13]
I'm using this is conjunction with the [media-extended](https://github.com/alx-plugins/media-extended) plugin, and it's so close to working great. 

However, when pasting embeddable links with this plugin I still need to manually add a ! in front of every pasted link, to create the `![]()` extended image syntax.  

It would be great if you could whitelist certain sites with this plugin to automatically add the ! in front when pasting. 

That way you could embed Youtube links (for example) as quick as you could paste them, would be really useful.

**Comment by AidenLx** [comment]
I've added a new feature that inserts `[](url)` when no selection is present, just wait until [the pull request](#14) is accepted & published and choose the option in the setting tab. You can type `!` and paste the link directly without selecting anything.

**Comment by kristofferR** [comment]
That will work okay for now, but it would still be awesome if we didn't have to write ! all the time. :)

With the whitelist functionality mentioned both embeddable and non-embeddable links could be pasted perfectly  quickly without extra effort.

You could potentially add more advanced customization functionality, by letting users customize the `[](url)` fragment with certain snippets and custom shortcuts. `[$Domain](url)` set in the plugin settings could for example result in `[Wikipedia - Title](url)` while pasting Wikipedia-links, $Date would be useful too, etc etc. 

Tons of potential.

However, a whitelist for embeddable links would be much simpler to implement quickly though.

**Comment by denolehov** [comment]
whitelist functionality has been added, please update the plugin :)

big thanks to @AidenLx once again for your contribution! ❤️
