### ISSUE TITLE
[Obsidian Forum]: Pasting from clipboard deletes existing text

### ISSUE THREAD

**Issue by whitenoisedev** [denolehov/obsidian-url-into-selection#19]
https://forum.obsidian.md/t/pasting-clipboard-deletes-existing-text/16896

**Comment by Palvehelmed** [comment]
I have the same problems when i paste, it deleted several words, or one sentence if I'm not using word split plug-in.

**Comment by AidenLx** [comment]
already fixed in 1.5.0

**Comment by denolehov** [comment]
thank you @AidenLx once again! :D
