### ISSUE TITLE
Error 404: loading style.css from github

### ISSUE THREAD

**Issue by gamedeviced** [denolehov/obsidian-url-into-selection#28]
## Problem

The plugin tries to load the following ressource, resulting in Error 404: https://github.com/denolehov/obsidian-url-into-selection/releases/download/1.6.0/styles.css

<img width="1673" alt="Bildschirmfoto 2021-08-21 um 12 10 24" src="https://user-images.githubusercontent.com/70090026/130318512-d28e6261-1bad-442c-a3ee-3f8519972c14.png"> 

## Expected behavior

Plugin shouldn't load external ressources at all if not needed (which seems for me to be the case).

## Versions

Obsidian: v0.12.12
Plugin: 1.6.0, installed via Obsidian

**Comment by denolehov** [comment]
Hey @gamedeviced, It's Obsidian trying to load said resource.
This plugin doesn't define `styles.css` as there is no need to style anything. 

Feel free to ignore this error :)
