### ISSUE TITLE
[BUG] Does not work within Kanban plugin boards

### ISSUE THREAD

**Issue by firinael** [denolehov/obsidian-url-into-selection#29]
As title describes, the plugin literally does not function at all inside Kanban boards.

**Comment by phibr0** [comment]
That probably isn't something this Plugin should do, the Kanban Plugin implements its own Editor.

**Comment by firinael** [comment]
I mean, it's just a hotkey for inserting the link inside the selected word, I don't see why it shouldn't work with other plugins. Guess I'll see with the Kanban author if there's anything to be done.

**Comment by phibr0** [comment]
Yes thats true, but this Plugin interacts with Obsidian's Editor, nothing else.

**Comment by denolehov** [comment]
That's right, if the Kanban Plugin has its own editor, we're not listening to events coming from it. I am not even sure if it's possible to get an instance of the kanban's editor and tap into its events.

**Comment by firinael** [comment]
I got a response from Meyers.

> "The kanban plugin uses a basic textarea, rather than the full-fledged editor that obsidian uses, so it can't really respond in the same ways"
So yeah, sadly sounds like it's not doable.
