### ISSUE TITLE
Support file URLs and non-http URIs

### ISSUE THREAD

**Issue by Cito** [denolehov/obsidian-url-into-selection#3]
As far as I see, this plugin checks if the clipboard contains a valid http/https URL and does not paste otherwise.

* It would be nice if the plugin would also check if this is a valid file path (either POSIX or Windows) and then paste it as a link with the [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme). This way you can create links to other documents or directories on your local filesystem.

* It should also url encode blanks to %20 (maybe also other special characters), and in case of a Windows path, it should also convert backslashes to forward slashes.

* There should be an option to use the [angle bracket notation](https://spec.commonmark.org/0.29/#example-486) of CommonMark for links that contain spaces, instead of url encoding them. This makes the link better readable.

* Also, if the clipboard content is neither a valid URL nor file path, maybe it should show an error message explaining what is wrong instead of simply doing nothing.

* Maybe, if the clipboard content is a [valid URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) with a different scheme than http: or https: (like ftp: or mailto:) it should also be pasted. [Registered](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) and unregistered schemes (e.g. for opening certain apps) should be recognized.

**Comment by DandyLyons** [comment]
It doesn't work for me even if it's a https URL.

**Comment by Cito** [comment]
@DandyLyons This must be different problem, as https URLs like the one for this issue definitly work for me. Make sure the plugin is enabled and you're in edit mode when pasting.

**Comment by MSzturc** [comment]
+1

Would love to use this with denonthink links. (x-devonthink-item://C6FEBBD8-109A-4309-B227)

**Comment by Benature** [comment]
+1

Would love to use this with marginnote links. (eg: marginnote3app://note/FC25E951-1CFF-431E-899B-2724A7E8432A)

**Comment by Benature** [comment]
Just as a walkaround, I modified the regex string in `main.js` to satisfy the URL scheme format, which is much less strict
```js
UrlIntoSelection.prototype.isUrl = function (text) {
    var urlRegex = new RegExp(
      "^[a-z0-9-]+:\\/\\/[a-zA-Z0-9-]+"
    );
    return urlRegex.test(text);
  };
```
Now I can paste marginnote links and devonthink links

**Comment by NeighNeighNeigh** [comment]
Hey @Benature 

This fix doesn't seem to work for file:/// URI's. (I imagine because of the 3 required slashes?)
Any way to have the regex include these as well?

Thanks ♡

**Comment by Cito** [comment]
@NeighNeighNeigh Yes, the urlRegex above does not allow for three slashes. An URL like `file:/path` URLs which is also valid does not pass either - see [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) for what is allowed here.

**Comment by NeighNeighNeigh** [comment]
Oh okay cool thanks for the info, I should be able to get it working by modifying my methods for obtaining a URL for a file. Thanks again :)

**Comment by Benature** [comment]
@NeighNeighNeigh hello, maybe you can try
```js
UrlIntoSelection.prototype.isUrl = function (text) {
    var urlRegex = new RegExp(
      "^[a-z0-9-]+:(\\/){2,3}[a-zA-Z0-9-]+"
    );
    return urlRegex.test(text);
  };
```
it allows two or three slashes.

**Comment by NeighNeighNeigh** [comment]
@Benature thank you for taking the time to refine this further, I really appreciate it. Now working great over here 😃

**Comment by NeighNeighNeigh** [comment]
Hi @denolehov. I was having great success using @Benature's modification- But now with the new update, if I use Benature's regex it fails. It would be nice to have the option to just forego the regex check completely– as I know I have a url in my clipboard and when I use my custom shortcut it should paste whatever is in my clipboard as URL.

**Comment by denolehov** [comment]
@NeighNeighNeigh Please try this regex: `^[a-z0-9-]+:(\/){2,3}[a-zA-Z0-9-]+`.

**Comment by NeighNeighNeigh** [comment]
Yep working here now, thank you :)
