### ISSUE TITLE
Add support for Live Preview

### ISSUE THREAD

**Issue by DutchPete** [denolehov/obsidian-url-into-selection#33]
This is a very useful plug-in. Unfortunately it does not work with Live Preview (code mirror6).
Could you add support for LP?

**Comment by uwe999** [comment]
+1

**Comment by ChengYingo** [comment]
+1

**Comment by MikhaD** [comment]
+1

**Comment by EhuddR** [comment]
It's very useful indeed. Please add support for Live premiew mode.

**Comment by InvisOn** [comment]
It does not work at all anymore. Even with live preview turned off.

**Comment by walkinverse** [comment]
I also just hit this today with the new live preview.  UGH.  Please add support..

**Comment by DutchPete** [comment]
The last release is dated 27 April: that is a long time ago. The dev has so far not reacted to the many comments or upvotes. I wonder if he/she has abandoned the plug-in?

**Comment by MikhaD** [comment]
> 

If that is the case would people be in favor of me creating a new plugin that does the same thing and works in the latest version? You'd have to install it manually until its approved as a community plugin, but it would be better than nothing.

**Comment by DutchPete** [comment]
If creating a new plug-in is easier than adapting the current one, sure. Manual installation is no big deal at all.

**Comment by krzemian** [comment]
@MikhaD would be great, as a workaround I can see that the current plugin exposes "Paste URL into selection:" in the command palette, which still works in Live Preview. So setting up a custom hotkey for pasting URLs only works for now.

**Comment by MikhaD** [comment]
Okay guys, I have created a pull request (#34 ) that fixes this plugin for the latest version with live preview. If you want to install it now you can download the main.js and manifest.json files from [here](https://github.com/MikhaD/obsidian-url-into-selection/releases/tag/1.7.0).
Please let me know if you find any issues with it.

**Comment by DutchPete** [comment]
I cannot load this via the BRAT plug-in - it says there is no manifest.json file, even though there is.

**Comment by badmuggle** [comment]
works great after installing files.  thanks!

**Comment by About7Deaths** [comment]
> Okay guys, I have created a pull request (#34 ) that fixes this plugin for the latest version with live preview. If you want to install it now you can download the main.js and manifest.json files from [here](https://github.com/MikhaD/obsidian-url-into-selection/releases/tag/1.7.0). Please let me know if you find any issues with it.

The update works great, thanks for that. What is your plan for the future if the original developer does not return to the project?

**Comment by InvisOn** [comment]
I alternative to this seemingly abandoned plugin could be https://github.com/zolrath/obsidian-auto-link-title

**Comment by MikhaD** [comment]
> > Okay guys, I have created a pull request (#34 ) that fixes this plugin for the latest version with live preview. If you want to install it now you can download the main.js and manifest.json files from [here](https://github.com/MikhaD/obsidian-url-into-selection/releases/tag/1.7.0). Please let me know if you find any issues with it.
> 
> The update works great, thanks for that. What is your plan for the future if the original developer does not return to the project? Additionally, would you be willing to implement the ability to paste regular non-formatted hyperlinks when using Ctrl + Shift + V if used instead of the standard Ctrl + V?

I would be happy to implement that. Hopefully the dev returns and accepts my pull request. I'm not sure what to do otherwise. Maybe there's a way for me to request that the link to this plugin in obsidian-releases is changed to point to my fork of the plugin?

**Comment by MikhaD** [comment]
The author has merged my pull request! He said there should be a release later today 🎉

**Comment by denolehov** [comment]
Thank you once again for your contribution @MikhaD! ❤️
