### ISSUE TITLE
“Failed to install” with latest upgrade

### ISSUE THREAD

**Issue by davebhc71** [denolehov/obsidian-url-into-selection#36]
Failed to install on Mac and iPad with latest insider releases of Obsidian.

**Comment by cubic3d** [comment]
Same here, can't update to 1.7.0 on Windows with latest Obsidian v0.13.19.

**Comment by zzhanghub** [comment]
Me too.

**Comment by liang0802** [comment]
Me too.

**Comment by lildude** [comment]
This is because the version in the manifest file references a release (1.7.0) that doesn't exist yet. According to https://github.com/denolehov/obsidian-url-into-selection/pull/34#issuecomment-1022026305 this will be made sometime today 🤞.

**Comment by davebhc71** [comment]
Still failing to Install with latest update!

**Comment by grantx2016** [comment]
Same here.

**Comment by petruut** [comment]
still having an issue with this - failed to install

**Comment by PixelParas** [comment]
Well I'm not the only one.

**Comment by DutchPete** [comment]
When it failed to update, I uninstalledm tried to reinstall, still no locuk. Then tried via BRAT, and got the message `main.js` is missing.

**Comment by svonjoi** [comment]
same in windows 10

**Comment by DutchPete** [comment]
I just reinstalled version 1.6.0, which works fine.

**Comment by cubic3d** [comment]
As we are all aware now, that there is a problem with the recent PR merge and the new release `1.7.0` is missing, please stop spamming this issue with "me too"/"same" or sort of - everyone is affected, just wait for a release.

**Comment by DutchPete** [comment]
@cubic3d : oh, you mean after your 1st post the rest of us need not/did not have the right to let the dev know that it is not just 1 erratic happening at cubic3d's end but that others are experiencing this too?

Well, the only reason you can state “As we are all aware now, that there is a problem with the recent PR merge” is precisely because others, apart from you, chimed in. So, thanks for your contribution to the spam with your spam chain extending “as we are all aware now ……” Most useful indeed.

**Comment by travipross** [comment]
Just wanted to join in and report that I'm also observing the same issue. It looks like the [developer of this project is aware and a release is coming soon](https://github.com/denolehov/obsidian-url-into-selection/pull/34#issuecomment-1022073550).

For anyone else concerned about other users seeing a failed upgrade of the plugin in Obsidian and coming here to share their experience, this may be of some help: 
![image](https://user-images.githubusercontent.com/17794229/151668687-0136b198-8fec-4ece-bd85-0e698f041a94.png)

**Comment by denolehov** [comment]
The issue is fixed, a new release is available and installable now, sorry everyone.

**Comment by davebhc71** [comment]
Downloaded and INSTALLED!!! Thank you!

**Comment by travipross** [comment]
Thanks @denolehov! I've really missed your plugin and I'm glad to have it back

**Comment by grantx2016** [comment]
Fixed. Thanks.
